export { default as Features} from './features/Features'
export { default as Footer} from './footer/Footer'
export { default as HeroSection} from './heroSection/HeroSection'
export { default as Gallery} from './gallery/Gallery'
export {default as TeamCard} from './teamcard/TeamCard'
export {default as CourseCard} from './coursecard/CourseCard'
export { default as ContactPage } from './contact/ContactPage'
export { default as FooterHeart } from './footerHeart/FooterHeart'