import type { Metadata } from "next";
import { Fira_Code } from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Toaster } from "sonner";

const firaCode = Fira_Code({
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Cisco NetAcad VIIT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${firaCode.className} bg-base-300`}
      >
        <Navbar/>
        {children}
        <Footer/>
        <Toaster />
      </body>
    </html>
  );
}
