name: Auto Merge Snyk Bot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    if: >
      github.actor == 'snyk-io[bot]' &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Wait for all checks to pass
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const checks = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha,
            });
            if (checks.data.check_runs.some(check => check.conclusion !== 'success')) {
              core.setFailed('Not all checks have passed.');
            }

      - name: Merge the pull request
        uses: actions/github-script@v6
        with:
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash',
            });